import './open_photo_editing.js';
import './photo_editing.js';
import './sending_data.js';
import './validation.js';
import './effect_editing.js';
import './import_data.js';
import './data_rendering.js';
import './big_photo.js';
import './filter.js'